Repository deislabs/krustlet, pull requests merged in 2021-01, with the labels that each got.

#474 Check if service field is provided by auth challenge
  crates/oci-distribution/src/client.rs
Labels: bug

#479 Krator Example
  Cargo.lock
  crates/krator/Cargo.toml
  crates/krator/examples/manifests/manfred.yaml
  crates/krator/examples/manifests/melissa.yaml
  crates/krator/examples/manifests/moose.yaml
  crates/krator/examples/moose.rs
  crates/krator/src/lib.rs
Labels: documentation

#478 Clippy 1.49.0
  crates/kubelet/src/bootstrapping/mod.rs
  crates/kubelet/src/node/mod.rs
  crates/oci-distribution/src/client.rs
  crates/oci-distribution/src/reference.rs
  crates/wascc-provider/src/states/container/waiting.rs
Labels: chore

#486 Patch Azure One Click Deploy
  contrib/azure/azuredeploy.json
Labels: bug
